### ISSUE TITLE
Anyway to make this Homebridge Compatible?

### ISSUE THREAD

**Issue by remirr** [snikch/climate.escea#6]
Hi there,

We have just finished our house and have two Escea Network Connected Fireplaces in our house. I would love to be able to add these to Homekit and control them from the single Home app. I seem to be having trouble finding a Homebridge Plugin and I was wondering if this would work? 

Thanks so much!

**Comment by khcnz** [comment]
If you have home-assistant then you can expose this module out through the homekit plugin to iOS devices (I have this working) https://www.home-assistant.io/integrations/homekit/

**Comment by remirr** [comment]
@khcnz sorry, where do I run Home-assistant? Is that google Home Assistant? I have Homebridge running on a windows pc.

**Comment by snikch** [comment]
Home assistant is a separate piece of software. So you'd run HomeAssistant (with this plugin) which would expose itself as a HomeKit plugin. You wouldn't need homebridge in this configuration (although you can have it running as well, no problem - I do this).

Since this is Python and Homebridge is Node, it's not a simple process to convert it to a homebridge plugin.

https://www.home-assistant.io/

**Comment by davewilton** [comment]
I just did this for homebridge @remirr 

https://www.npmjs.com/package/homebridge-escea-gas-fire
